### ISSUE TITLE
maybe add an enabled option to be compatible with the ldap auth

### ISSUE THREAD

**Issue by f1-outsourcing** [bit/matrix-synapse-imap#4]
https://github.com/matrix-org/matrix-synapse-ldap3#usage

```
     - module: "imap_auth_provider.IMAPAuthProvider"
       config:
         enabled: false
         create_users: true
         server: "test.test.local"
         plainuserid: true

```
